### ISSUE TITLE
Storing full path to base location force errors on staging environment

### ISSUE THREAD

**Issue by thorque** [ConnectThink/WP-SCSS#204] opened 2021-08-07 13:40 UTC
Hello,

I am using an host providing me a staging environment. But in this case there are an issue. The path to the base location is stored as full path in wp_options table. But the path are different between live and staging:

- Live: /home/wp/disk/wordpress/wp-content/...
- Staging: /home/wp/disk/wordpress_staging/wp-content/...

So the generated css are not available. Is there a chance to change this, that only the part from wp-content/... will be stored in wp_options and the path to the wordpress installation is added during runtime? This would solve this issue.

Thanks 
Thorsten

**Comment by shadoath** [comment] 2021-09-08 14:10
Closing this as it is a duplicate of #196. Going to move your comment there as it does a good job outlining the problem.

**Closed by shadoath** 2021-09-08 14:10 UTC
Labels: duplicate
