### ISSUE TITLE
Multiple fscss-folders?

### ISSUE THREAD

**Issue by websterman** [ConnectThink/WP-SCSS#118] opened 2018-12-04 10:35 UTC
I want to start using scss for my wordpress projects. However I can't seem to specify more than one folder to look for changes to compile in. 

This is problematic in a parent/child theme sense, since I want to have a bunch of mixins etc in the parent theme that I want to access in the child theme. Is there a way to currently accomplish this or am I missing something?

Thanks!

**Comment by garrettw** [comment] 2018-12-06 15:24
Probably a duplicate of #114

**Comment by shadoath** [comment] 2021-02-15 17:46
Closing as duplicate

**Closed by shadoath** 2021-02-15 17:46 UTC
Labels: duplicate
