### ISSUE TITLE
version 2.1.1 breaks Wordpress.com hosted sites

### ISSUE THREAD

**Issue by airplanenoise** [ConnectThink/WP-SCSS#168] opened 2021-02-15 19:51 UTC
now obvi I would prefer to be on my own hosting, but this is for an existing client. 
after 2.1.1 upgrade the enqueue URLs stopped being recognized, and the site looks like craigslist circa 2001 ;) 

anybody else having this issue? 

thanks! 

k

**Comment by airplanenoise** [comment] 2021-02-15 20:00
i rolledback to scss 2.0.1 and all is well, but that's an odd one for me :)

**Comment by mountbatt** [comment] 2021-02-16 13:20
Damn. After the problems with the missing /cache directory now a problem with the latest update. You have to press "Save settings" in the Plugins-Settings to save the latest settings. This is horrible cause i have much more than 50 client websites with this plugin running … i want to cry …

**Comment by pixeldesignstudio** [comment] 2021-02-16 15:06
> Damn. After the problems with the missing /cache directory now a problem with the latest update. You have to press "Save settings" in the Plugins-Settings to save the latest settings. This is horrible cause i have much more than 50 client websites with this plugin running … i want to cry …

Multiple Clients called me today ...
I had to login into every site and change the compression method so the include URL works again.

https://css/global.css 404

What a day!

**Comment by jcouturier** [comment] 2021-02-16 16:52
Confirming the same issue - not just WP hosted sites, self-hosted as well. CSS doesn't load at all, but re-saving Settings in the plugin fixes the issue.

**Comment by rtro92** [comment] 2021-02-16 18:25
I'm also having the same issue. In some cases re-saving settings/changing compiling mode/clearing cache didn't work so I had to roll back to 2.0.1. This took down multiple sites.

**Comment by getrefined** [comment] 2021-02-16 20:42
Yep having exactly the same issue with 2.1.1

Working through 100+ sites to get the bad links to fix themselves... fun fun fun

**Comment by shadoath** [comment] 2021-02-16 22:40
Yikes!  My apologies to see this happening to so many people. Pretty obvious that there is some missing backward compatibility. 
Can someone post settings before saving and after? 

I think the issue is not enqueueing styles correctly and that this [PR](https://github.com/ConnectThink/WP-SCSS/pull/169) will correct this issue. If someone can test and confirm this, I'lll get a release out tonight.

**Comment by sinternal** [comment] 2021-02-17 06:52
Same Problem. The update this morning broke it once again. And my site is hosted on my own server

**Comment by davey013** [comment] 2021-02-17 07:53
Same here, 2.1.2 made it even worse, see my comment here: https://github.com/ConnectThink/WP-SCSS/issues/170

**Comment by getrefined** [comment] 2021-02-17 08:18
2.1.2 update now prevents you from just saving in setting to fix the issue. We're rolling back to 2.0.1 and preventing any auto updates

**Comment by pixellogik** [comment] 2021-02-17 12:22
As I commeted in Wordpress here is my fix:

In wp-scss.php on Line 301 $base_compiling_folder is missing.
Add it to global like this:

global $wpscss_compiler, $wpscss_options, $base_compiling_folder;

**Comment by djalondon** [comment] 2021-02-17 14:13
> As I commeted in Wordpress here is my fix:
> 
> In wp-scss.php on Line 301 $base_compiling_folder is missing.
> Add it to global like this:
> ` global $wpscss_compiler, $wpscss_options, $base_compiling_folder;`

My site isn't hosted on wordpress.com but was affected. This fix didn't work for me so I had to rollback to version 2.01

**Comment by shadoath** [comment] 2021-02-17 16:11
Gah! Total fail in missing adding the global to the call. Pushed up 2.1.3 with this. Thank you @djalondon & @pixellogik for pointing this out.

**Comment by pixellogik** [comment] 2021-02-17 16:12
You're welcome

**Comment by rtro92** [comment] 2021-02-17 16:29
can confirm 2.1.3 is working for me on multiple sites

**Comment by djalondon** [comment] 2021-02-17 16:39
Great, works for me now, thanks!

**Comment by firelite** [comment] 2021-02-17 23:54
Hi,

I updated from v1.2.4 to v2.1.3 and now my theme scss styles broke.  I'm getting this error in console:

`(index):164 GET https://css/bootstrap_loader.css?ver=1613605867`

My base location is set to "Current Theme".

Will this be fixed?

**Comment by shadoath** [comment] 2021-02-18 05:17
@firelite have you saved your settings? 
Insert before [line 303 of the wp-scss.php](https://github.com/ConnectThink/WP-SCSS/blob/master/wp-scss.php#L303) the following code and post the output.
`var_dump($wpscss_options, $base_compiling_folder);`

**Comment by davey013** [comment] 2021-02-18 09:22
Can confirm 2.1.3 is working :-) Thanks for fixing this quickly!

**Comment by firelite** [comment] 2021-02-18 17:33
Yes, I did hit save on the settings page after I updated to 2.1.3.
ᐧ

**Comment by firelite** [comment] 2021-02-18 17:39
@shadoath  and here's my output:

`array(8) { ["base_compiling_folder"]=> string(56) "/www/wp-content/themes/blockz-child-theme" ["scss_dir"]=> string(6) "/scss/" ["css_dir"]=> string(5) "/css/" ["compiling_options"]=> string(34) "ScssPhp\ScssPhp\Formatter\Expanded" ["sourcemap_options"]=> string(15) "SOURCE_MAP_NONE" ["errors"]=> string(14) "show-logged-in" ["enqueue"]=> string(1) "1" ["always_recompile"]=> string(1) "1" } string(56) "/www/wp-content/themes/blockz-child-theme"`

**Comment by firelite** [comment] 2021-02-25 23:33
@shadoath Any idea?

**Comment by shadoath** [comment] 2021-03-01 03:28
@firelite I have been pondering this but come up with no idea what the error might be caused by or how to fix it yet.  Let's take this to a PM thread. I have emailed your inquire@firelite.co.

**Comment by shadoath** [comment] 2021-03-04 02:29
@firelite I merged in #167 and think that may fix your issue. Can you try a clone of the master branch at [2.1.4](https://github.com/ConnectThink/WP-SCSS/releases/tag/2.1.4)?

**Comment by stevearbour** [comment] 2021-03-05 04:13
This has not been fixed as I am having the same issue. Cannot upgrade from 2.0 to 2.1.1 or neither 2.1.4.

**Closed** 2021-06-18 03:26 UTC
Labels: bug
