### ISSUE TITLE
Does not recompile when change in partials

### ISSUE THREAD

**Issue by fwitkowski** [ConnectThink/WP-SCSS#130] opened 2019-12-19 17:47 UTC
I have scss files in /scss/ folder
In subfolder I have partials, which I @include in main.scss
When I do changes in partial file (and save them), it does not re-compile automatically,
only if I do some change in main.scss and save it.

**Comment by garrettw** [comment] 2019-12-19 17:54
May be a duplicate of #46. Check out what they did on that one and see if that helps you.
You might also look at #104 and #119.

**Comment by fwitkowski** [comment] 2019-12-19 18:04
Thanks this works
The only issue is I won't be able to push wp-config to staging, so if someone else will work on this site at some point, that developer would have to know to do this.

**Comment by razorfrog** [comment] 2019-12-20 19:28
Seems like there's a new issue with the latest release 1.2.5 9 days ago. 1.2.4 worked fine on many of our sites, but 1.2.5 doesn't compile anywhere. Downgrading fixes it. 
https://wordpress.org/support/topic/new-version-1-2-5-not-compiling-properly/

**Comment by johntbb** [comment] 2020-01-09 11:39
It's this commit that's stopped changes in imported files from triggering complication:

12e0108

To fix this issue, you need to replace this code:

`new RecursiveIteratorIterator(new RecursiveDirectoryIterator($this->scss_dir), FilesystemIterator::SKIP_DOTS)`

To this:

`new RecursiveIteratorIterator(new RecursiveDirectoryIterator($this->css_dir, RecursiveDirectoryIterator::SKIP_DOTS))`

on lines 156 and 166.

**Comment by shadoath** [comment] 2021-02-15 17:15
Taking over the maintenance of this plugin. The creators did not have time to work on it. Now, i'm looking at the backlog of issues and working to solve them. @johntbb, thank you for pointing out the solution. I have a [PR](https://github.com/ConnectThink/WP-SCSS/pull/166) with updates you can look at.

**Comment by shadoath** [comment] 2021-08-29 10:10
I believe this is now fixed.

**Closed by shadoath** 2021-08-29 10:10 UTC
Labels: bug
